// copy this to config.js and modify

module.exports = {
  token: 'your personal github API token with super powers',
  from: 'punkave',
  transfers: [
    {
      to: 'apostrophecms',
      teams: [ 'developers' ],
      repos: [
        'apostrophe',
        'apostrophe-sandbox',
        'apostrophe-documentation',
        'apostrophe-boilerplate',
        'apostrophe-blog',
        'apostrophe-pages',
        'apostrophe-cli',
        'apostrophe-workflow',
        'apostrophe-events',
        'apostrophe-headless',
        'apostrophe-override-options',
        'apostrophe-site-map',
        'apostrophe-passport',
        'apostrophe-places',
        'apostrophe-link-widgets',
        'apostrophe-seo',
        'apostrophe-atom',
        'apostrophe-vs',
        'apostrophe-styleguide',
        'apostrophe-redirects',
        'apostrophe-debug',
        'apostrophe-pubmed',
        'apostrophe-pubmed-import',
        'apostrophe-browser-requirements',
        'apostrophe-second-chance-login',
        'apostrophe-gallery-demo',
        'apostrophe-address-widgets',
        'apostrophe-page-migrator',
        'apostrophe-legacy-import',
        'apostrophe-pieces-import',
        'apostrophe-caches-redis',
        'apostrophe-pieces-submit-widgets',
        'apostrophe-extra-link-attributes',
        'apostrophe-site-review',
        'apostrophe-replace-original-with-full'
      ]
    },
    {
      to: 'apostrophecms-legacy',
      teams: [ 'developers' ],
      repos: [
        'apostrophe-snippets',
        'apostrophe-site',
        'apostrophe-localization',
        'apostrophe-people',
        'apostrophe-schemas',
        'apostrophe-blog-2',
        'apostrophe-blocks',
        'apostrophe-google-calendar',
        'apostrophe-browserify',
        'apostrophe-search',
        'apostrophe-editor-2',
        'apostrophe-backup',
        'apostrophe-schema-widgets',
        'apostrophe-google-spreadsheet',
        'apostrophe-help',
        'apostrophe-raphael',
        'apostrophe-proxy-auth',
        'apostrophe-cats',
        'apostrophe-patch',
        'apostrophe-moderator',
        'apostrophe-donate',
        'apostrophe-forms',
        'apostrophe-twitter',
        'apostrophe-tumblr',
        'apostrophe-websockets',
        'apostrophe-preferences',
        'apostrophe-sections',
        'apostrophe-rss',
        'apostrophe-flickr',
        'apostrophe-cas',
        'apostrophe-groups',
        'apostrophe-xlsx',
        'apostrophe-map',
        'apostrophe-toc',
        'apostrophe-block',
        'apostrophe-soundcloud',
        'apostrophe-button',
        'apostrophe-salesforce',
        'apostrophe-facebook',
        'apostrophe-ads',
        'apostrophe-instagram',
        'apostrophe-twitter-widgets',
        'apostrophe-fancy-page',
        'apostrophe-magic-redirects',
        'apostrophe-twitter-2',
        'apostrophe-update-forms',
        'apostrophe-global-rss-feed',
        'apostrophe-simple-blog',
        'apostrophe-google-login',
        'apostrophe-ui-2',
        'apostrophe-demo-login',
        'myapostrophe-mac'
      ]
    }
  ]
};
